//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksSearchTelegramBot.res {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooksSearchTelegramBot.res.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Книга добавлена в отложенные.
        /// </summary>
        internal static string AddToDefferedMessage {
            get {
                return ResourceManager.GetString("AddToDefferedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Книга добавлена в прочитанные.
        /// </summary>
        internal static string AddToReadedMessage {
            get {
                return ResourceManager.GetString("AddToReadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬅ Назад.
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📚 Отложенные.
        /// </summary>
        internal static string MyDefferedButton {
            get {
                return ResourceManager.GetString("MyDefferedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отложенные книги:.
        /// </summary>
        internal static string MyDefferedMessage {
            get {
                return ResourceManager.GetString("MyDefferedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📚 Моё.
        /// </summary>
        internal static string MyMenuButton {
            get {
                return ResourceManager.GetString("MyMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть прочитанные или отолженные книги?.
        /// </summary>
        internal static string MyMenuMessage {
            get {
                return ResourceManager.GetString("MyMenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✅ Прочитанные.
        /// </summary>
        internal static string MyReadedButton {
            get {
                return ResourceManager.GetString("MyReadedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочитанные вами книги:.
        /// </summary>
        internal static string MyReadedMessage {
            get {
                return ResourceManager.GetString("MyReadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 💫 Жанр.
        /// </summary>
        internal static string SearchByGenreButton {
            get {
                return ResourceManager.GetString("SearchByGenreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите жанр:.
        /// </summary>
        internal static string SearchByGenreMessage {
            get {
                return ResourceManager.GetString("SearchByGenreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⭐ Рейтинг.
        /// </summary>
        internal static string SearchByRatingButton {
            get {
                return ResourceManager.GetString("SearchByRatingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Книги отсортированные по рейтингу:.
        /// </summary>
        internal static string SearchByRatingMessage {
            get {
                return ResourceManager.GetString("SearchByRatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📄 Название.
        /// </summary>
        internal static string SearchByTitleButton {
            get {
                return ResourceManager.GetString("SearchByTitleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название книги:.
        /// </summary>
        internal static string SearchByTitleMessage {
            get {
                return ResourceManager.GetString("SearchByTitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔎 Поиск.
        /// </summary>
        internal static string SearchMenuButton {
            get {
                return ResourceManager.GetString("SearchMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите критерий поиска.
        /// </summary>
        internal static string SearchMenuMessage {
            get {
                return ResourceManager.GetString("SearchMenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите наиболее подходящее.
        /// </summary>
        internal static string SelectMoreApproriate {
            get {
                return ResourceManager.GetString("SelectMoreApproriate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск или ваши книги?.
        /// </summary>
        internal static string StartMenuMessage {
            get {
                return ResourceManager.GetString("StartMenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте, это бот для поиска книг.
        /// </summary>
        internal static string WelcomeMessageWithoutUsername {
            get {
                return ResourceManager.GetString("WelcomeMessageWithoutUsername", resourceCulture);
            }
        }
    }
}
